id: P008239
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 13:09:58.008150
source_metadata:
  id: bdr:W27304
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་ཁྲིད་ཡིག་འཇམ་དཔལ་ཞལ་ལུང་དང་པཎ་ཆེན་བདེ་ལམ
  author: ''
  volumes:
    589ef243c47d4c93ac7ad5388afa3682:
      image_group_id: I4259
      title: ''
      volume_number: 1
      total_pages: 304
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
