id: I9F3D3434
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T01:48:34+00:00'
last_modified: '2022-06-08T08:09:43.488626+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27304
  title: བྱང་ཆུབ་ལམ་གྱི་རིམ་པའི་ཁྲིད་ཡིག་འཇམ་དཔལ་ཞལ་ལུང་དང་པཎ་ཆེན་བདེ་ལམ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    41EA:
      image_group_id: I4259
      title: ''
      total_pages: 304
      order: 1
      base_file: 41EA.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
